### ISSUE TITLE
can not connect server by time out

### ISSUE THREAD

**Issue by Alisheng** [StephenMP/ts-ioredis-pool#1]
i pull package from npm；and connect redis server get this error；my redis server version is 5.0.1；and i can see the source code in dev en.
Error: connect ETIMEDOUT
    at Socket.<anonymous> (E:\workDir\orangeBox\webServer\node_modules\ts-ioredis-pool\dist\index.js:1:102607)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at Socket._onTimeout (net.js:495:8)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}

**Comment by Alisheng** [comment]
just err host!!!
